.github/workflows/main.yml, .pre-commit-config.yaml, README.md
发布新版本后上传测试脚本至 assets。以后只保留 main 分支，删除 dev 分支。
=> ci: 上传插件测试脚本

.github/workflows/main.yml
还需要设置 TAG_NAME 和 GITHUB_TOKEN。
=> ci: 修复上传文件出错

src/utils.py
=> feat: 运行命令出错时添加输出

plugin_test.py
加载插件后，require 其依赖来测试是否符合标准。
```python
from nonebot import init, load_plugin, require
init(driver="~none")
valid = load_plugin("nonebot_plugin_xxx")
require("nonebot_plugin_yyy")
if not valid:
exit(1)
else:
exit(0)
```
=> feat: 测试插件是否在 import 前使用 require 声明依赖

tests/conftest.py, tests/process/test_publish_check.py, tests/process/test_pull_request.py, tests/utils/test_comment_issue.py, tests/utils/test_get_pull_requests_by_label.py, tests/utils/test_resolve_conflict_pull_requests.py
=> test: 重新加回测试

CHANGELOG.md, src/plugins/publish/__init__.py, src/plugins/publish/depends.py, tests/publish/process/test_publish_check.py
因为就算延后执行，议题的名称也不会变。这样如果议题与发布无关就可直接跳过，少执行一次请求。
=> change: 提前判断议题是否与发布有关

src/plugins/publish/constants.py, tests/publish/models/test_adapter.py, tests/publish/models/test_bot.py, tests/publish/models/test_name.py, tests/publish/models/test_plugin.py, tests/publish/models/test_tags.py, tests/publish/process/test_publish_check.py, tests/publish/utils.py, tests/publish/utils/test_re.py, tests/publish/utils/test_resolve_conflict_pull_requests.py
适配最新的议题模板。
<https://github.com/nonebot/nonebot2/pull/2010>
=> feat: 适配议题模板

CHANGELOG.md, src/plugins/publish/__init__.py, tests/publish/events/issue-open.json, tests/publish/process/test_publish_check.py
自从[使用 issue form 进行商店发布](https://github.com/nonebot/nonebot2/pull/2010)后，不再需要根据标题判断类型了。
=> change: 通过议题标签判断商店发布类型

CHANGELOG.md, src/plugins/publish/validation.py, tests/conftest.py, tests/publish/models/test_plugin.py
因为 supported_adapters 返回值为集合，所以每次输出的 json 文件排序都不一致。
切换为列表并排序来保证相同结果的一致性。
=> fix: 修复输出支持适配器列表未排序的问题

CHANGELOG.md, pyproject.toml, src/plugins/publish/render.py, src/plugins/publish/utils.py, src/utils/store_test/constants.py, src/utils/store_test/models.py, src/utils/store_test/validation.py, src/utils/validation/__init__.py, tests/publish/render/test_render_error.py, tests/utils/store_test/output.txt, tests/utils/store_test/test_validate_plugin.py, tests/utils/store_test/test_validate_plugin_info.py, tests/utils/validation/utils.py
validation.output 会直接返回验证通过的数据与错误。如果所有数据均验证通过，则返回 None。
同时将插件加载测试相关验证移至 validate_info 函数内，这样商店测试那边也能获得完整的验证信息。
插件信息增加测试时插件的版本号。
=> feat!: 调整商店测试输出内容

CHANGELOG.md, src/plugins/publish/__init__.py, src/plugins/publish/utils.py, tests/publish/process/test_auto_merge.py, tests/publish/utils/test_resolve_conflict_pull_requests.py
此时没有测试环境， 并且之前的测试结果应该依旧有效。
fix #161
=> fix: 处理冲突时直接重新提交

CHANGELOG.md, src/plugins/publish/__init__.py, src/plugins/publish/utils.py, tests/publish/process/test_publish_check.py
=> feat: 发布信息更新后如果发现不通过将拉取请求转成草稿

CHANGELOG.md, src/utils/store_test/models.py, src/utils/store_test/store.py, src/utils/store_test/validation.py, tests/utils/store_test/output_failed.txt, tests/utils/store_test/test_store_test.py, tests/utils/store_test/test_validate_plugin.py, tests/utils/validation/utils.py
因为其插件加载测试无法通过，也就没法获取所需的 metadata。
=> fix(store_test): 跳过测试的插件需要从之前的数据中提取验证所需数据

CHANGELOG.md, src/utils/store_test/store.py, src/utils/store_test/utils.py, src/utils/store_test/validation.py, tests/conftest.py, tests/utils/store_test/test_validate_plugin.py
plugins.json 中的 time 字段调整为文件上传时间。results.json 中的 time 不变，为测试时间。
close #179
=> feat: 用 PyPI 项目的文件上传时间替换测试时间

CHANGELOG.md, src/utils/store_test/models.py, src/utils/store_test/store.py, src/utils/store_test/utils.py, src/utils/store_test/validation.py, tests/utils/store_test/test_store_test.py, tests/utils/store_test/test_validate_plugin.py
同时测试结果与插件数据做区分。
测试结果中的 version 字段使用从插件加载测试输出中提取出的版本号，如果跳过测试或无法提取到版本号则为 None。
插件数据中的 version 字段则根据情况，优先使用测试中提取的版本号，如果无法提取出版本号（创建环境失败），则使用 pypi 上的数据。
=> fix: 修复跳过插件测试时无法获取插件版本与时间的问题

CHANGELOG.md, pyproject.toml, src/utils/plugin_test.py, src/utils/store_test/store.py, src/utils/store_test/validation.py, tests/utils/store_test/test_store_test.py, tests/utils/store_test/test_validate_plugin.py
即使验证出错，也应该更新插件信息。比如版本，时间，验证结果与是否还需跳过测试。
=> fix: 修复验证出错时无法更新插件版本信息的问题

CHANGELOG.md, src/utils/plugin_test.py
=> fix(plugin_test): 修复未通过标签判断是否是插件发布的问题

CHANGELOG.md, src/plugins/publish/__init__.py, tests/publish/process/test_pull_request.py
先处理pr再触发registry更新
有时已经在进行商店更新，但是pr还未合并，nonebot仓库的{module_name}.json未写入新的插件信息，从而导致测试失败
如果没有其它pr触发，就无法写入到 nonebot/registry，导致丢失插件
https://github.com/nonebot/registry/actions/runs/7675902162/job/20922746791
```python3
...
File "/home/runner/work/registry/registry/src/utils/store_test/store.py", line 96, in test_plugins
test_plugins = [(key, self._store_plugins[key])]
KeyError: 'nonebot-plugin-nezha:nonebot_plugin_nezha'
```
=> fix: 等待 2 分钟后再触发 registry_update

CHANGELOG.md, src/plugins/publish/__init__.py, src/plugins/publish/utils.py, tests/publish/process/test_pull_request.py, tests/publish/utils/test_trigger_registry_update.py
这样如果在 json 更新后再次运行也不会获取到不属于该插件的信息
=> fix: 从议题中获取的插件信息

CHANGELOG.md, src/plugins/publish/utils.py, tests/publish/process/test_pull_request.py, tests/publish/utils/test_trigger_registry_update.py
=> fix: 延长 registry_update 触发等待时间到 5 分钟

CHANGELOG.md, src/utils/store_test/validation.py, tests/utils/store_test/test_extract_version.py
目前有很多插件都把信息填错了，没有使用 - 而是使用了 _。
=> fix: 修复项目名不用 - 分割时无法提取到版本的问题

CHANGELOG.md, src/utils/plugin_test.py
防止测试中出现类似报错。
```log
插件 nonebot_plugin_nai3 加载出错：
04-16 03:42:49 [SUCCESS] nonebot | NoneBot is initializing...
04-16 03:42:49 [INFO] nonebot | Current Env: prod
04-16 03:42:49 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_smms"
04-16 03:42:49 [ERROR] nonebot | Failed to import "nonebot_plugin_nai3"
04-16 03:32:55 [SUCCESS] nonebot | NoneBot is initializing...
04-16 03:32:55 [INFO] nonebot | Current Env: prod
04-16 03:32:56 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_smms"
04-16 03:32:56 [ERROR] nonebot | Failed to import "nonebot_plugin_nai3"
Traceback (most recent call last):
File "/home/runner/work/nonebot2/nonebot2/plugin_test/nonebot-plugin-nai3-nonebot_plugin_nai3-test/runner.py", line 15, in <module>
plugin = load_plugin("nonebot_plugin_nai3")
File …
```
=> feat: 默认使用 fake 适配器

CHANGELOG.md, src/utils/plugin_test.py
=> fix: 插件测试时设置为 10 分钟超时

CHANGELOG.md, src/utils/plugin_test.py
之前虽然将 Actions 中的 Python 版本升级了，但插件测试时仍然使用安装 Poetry 时的 Python 3.10 进行测试。
=> fix: 使用当前环境的 Python 版本进行测试

CHANGELOG.md, src/utils/plugin_test.py
驱动器应该通过 .env 文件设置，而不是在 init 的参数中设置。
=> fix(plugin_test): 调整测试时 Fake 驱动器设置位置

src/utils/plugin_test.py
由于 `NoneBot 2.3.0` 对 `HTTPClientMixin` 基类新增了抽象方法 `get_session`，所以现有的 `fake driver` 会导致启动混合驱动类时报错
```
05-01 20:02:48 [SUCCESS] nonebot | NoneBot is initializing...
05-01 20:02:48 [INFO] nonebot | Current Env: prod
Traceback (most recent call last):
File "/home/runner/work/registry/registry/plugin_test/nonebot-plugin-tetris-stats-nonebot_plugin_tetris_stats-test/runner.py", line 15, in <module>
init()
File "/home/runner/work/registry/registry/plugin_test/nonebot-plugin-tetris-stats-nonebot_plugin_tetris_stats-test/.venv/lib/python3.10/site-packages/nonebot/__init__.py", line 319, in init
_driver = DriverClass(env, config)
TypeError: Can't instantiate abstract class Driver with abstract method get_session
```
=> fix(plugin_test): 修复 NoneBot 2.3.0 添加的 HTTP 客户端会话支持导致测试失败的问题

.github/workflows/docker-test.yml, examples/noneflow.yml, examples/store-test.yml, src/providers/constants.py
这样方便在测试环境中测试脚本。
```env
STORE_BASE_URL: "https://raw.githubusercontent.com/nonebot/noneflow-test/master/assets"
REGISTRY_BASE_URL: "https://raw.githubusercontent.com/nonebot/noneflow-test/results"
DOCKER_IMAGES_VERSION: main
```
<https://github.com/nonebot/noneflow-test/blob/a7e88b879a2c7ed22854650b20fbc8d0527196e3/.github/workflows/noneflow.yml#L54>
<https://github.com/nonebot/noneflow-test/blob/a7e88b879a2c7ed22854650b20fbc8d0527196e3/.github/workflows/store-test.yml#L31-L34>
=> feat: 从环境变量中读取测试相关变量

src/plugins/github/depends/__init__.py, src/plugins/github/plugins/publish/__init__.py, src/plugins/github/plugins/publish/depends.py, tests/github/publish/process/test_auto_merge.py, tests/github/publish/process/test_publish_check.py, tests/github/publish/process/test_publish_pull_request.py, tests/github/remove/process/test_remove_check.py, tests/github/remove/process/test_remove_pull_request.py
只有当没有 Remove 标签时，才会走发布流程
同时修改了判断 Bot 的方式，仅通过 sender.type 判断
=> fix: rule 新增 is_publish_related_workflow

CHANGELOG.md, examples/noneflow.yml, pyproject.toml, src/plugins/github/plugins/publish/utils.py, src/plugins/github/plugins/remove/utils.py, src/plugins/github/plugins/remove/validation.py, src/plugins/github/utils.py, src/providers/constants.py, src/providers/docker_test/plugin_test.py, src/providers/store_test/store.py, src/providers/store_test/utils.py, src/providers/utils.py, tests/conftest.py, tests/github/publish/utils/test_publish_resolve_conflict_pull_requests.py, tests/github/remove/utils/test_update_file.py, tests/github/utils.py, tests/utils/store_test/conftest.py, tests/utils/store_test/store/store_adapters.json5, tests/utils/store_test/store/store_bots.json5, tests/utils/store_test/store/store_drivers.json5, tests/utils/store_test/store/store_plugins.json5, tests/utils/store_test/test_utils.py, tests/utils/test_json5.py, uv.lock
=> feat: 商店存放 json5 格式的数据

src/plugins/github/plugins/publish/validation.py, tests/conftest.py, tests/github/publish/process/test_publish_check.py, tests/github/publish/utils/test_publish_resolve_conflict_pull_requests.py, tests/github/remove/process/test_remove_check.py, tests/github/remove/utils/test_remove_resolve_pull_requests.py, tests/github/remove/utils/test_update_file.py
=> fix: 修复 json5 无法正常加载的问题

CHANGELOG.md, src/providers/docker_test/plugin_test.py
没出错的时候只输出 stdout，并且 show_plugin_dependencies 中只在报错的时候输出。
=> feat(plugin_test): 简化插件测试输出

CHANGELOG.md, src/plugins/github/plugins/publish/validation.py, src/providers/store_test/validation.py, src/providers/validation/__init__.py, src/providers/validation/models.py, tests/github/publish/utils/test_validate_info_from_issue.py, tests/utils/store_test/test_validate_plugin.py
tags 必须转成 Python 的 dict，如果为 list[Tag] 无法进行验证。
=> fix(store_test): 修复商店测试时标签验证出错的问题

CHANGELOG.md, src/providers/docker_test/__init__.py, tests/utils/docker_test/test_docker_plugin_test.py
NoneBot 中是允许 homepage 为空的。
```python
@dataclass(eq=False)
class PluginMetadata:
"""插件元信息，由插件编写者提供"""
name: str
"""插件名称"""
description: str
"""插件功能介绍"""
usage: str
"""插件使用方法"""
type: Optional[str] = None
"""插件类型，用于商店分类"""
homepage: Optional[str] = None
"""插件主页"""
config: Optional[Type[BaseModel]] = None  # noqa: UP006
"""插件配置项"""
supported_adapters: Optional[set[str]] = None
"""插件支持的适配器模块路径
格式为 `<module>[:<Adapter>]`，`~` 为 `nonebot.adapters.` 的缩写。
`None` 表示支持**所有适配器**。
"""
extra: dict[Any, Any] = field(default_factory=dict)
"""插件额外信息，可由插件编写者自由扩展定义"""
```
=> fix(docker_test): 修复插件测试获取到的插件元数据主页为空时报错的问题

CHANGELOG.md, src/providers/docker_test/plugin_test.py, tests/utils/docker_test/test_extract_version.py
<https://github.com/python-poetry/poetry/blob/96ffd5a28c2fa87b75bb4612c7606502b35c36c7/src/poetry/console/commands/add.py#L386>
<https://github.com/pypa/packaging/blob/1675b390e49ffff5acab16ee0351e7bc1e113fb0/src/packaging/utils.py#L46-L51>
=> fix(plugin_test): 使用规范化的名称匹配插件版本号

CHANGELOG.md, src/plugins/github/plugins/publish/render.py, src/plugins/github/plugins/publish/validation.py, src/providers/docker_test/__init__.py, src/providers/docker_test/plugin_test.py, src/providers/models.py, src/providers/store_test/validation.py, tests/utils/docker_test/test_docker_plugin_test.py, tests/utils/store_test/output.json, tests/utils/store_test/output_failed.json, tests/utils/store_test/test_validate_plugin.py, tests/utils/validation/test_plugin.py
Metadata 改为 TypedDict 并且在 DockerTestResult 中不验证。
针对数据的验证工作应该留给 validation 模块。
=> fix(docker_test): 修复插件元数据异常时导致插件测试验证报错的问题

CHANGELOG.md, src/providers/docker_test/Dockerfile
现在能正确安装 opencv-python 和 pillow。
<https://stackoverflow.com/questions/55313610/importerror-libgl-so-1-cannot-open-shared-object-file-no-such-file-or-directo>
=> fix(docker_test): 修复插件测试无法安装部分依赖的问题

CHANGELOG.md, src/providers/docker_test/plugin_test.py
暂时通过捕获异常来处理，以后还需要重构 plugin_test 脚本。
<https://github.com/glamorgan9826/nonebot-plugin-today-waifu/blob/9a527c4dd28678cb53d23e601668b2b421bf076c/nonebot_plugin_today_waifu/__init__.py#L47>
=> fix(plugin_test): 修复插件元数据不合法时 metadata.json 为空的问题

CHANGELOG.md, src/plugins/github/plugins/publish/validation.py, src/providers/store_test/store.py, src/providers/store_test/utils.py, src/providers/store_test/validation.py, src/providers/utils.py, src/providers/validation/models.py, tests/conftest.py, tests/github/publish/process/test_publish_pull_request.py, tests/github/publish/utils/test_publish_resolve_conflict_pull_requests.py, tests/github/publish/utils/test_trigger_registry_update.py, tests/utils/store_test/test_utils.py
插件发布流程没有填写 version 字段。现在直接删掉了默认值。
=> fix: 修复发布后 registry_update 中版本号为默认值的问题

src/providers/docker_test/__init__.py, src/providers/docker_test/plugin_test.py, tests/utils/docker_test/test_docker_plugin_test.py, tests/utils/docker_test/test_parse_requirements.py, tests/utils/docker_test/test_plugin_test.py
记录 python，nonebot2 和 pydantic 版本。
close #287
=> feat: 从插件测试中提取环境信息

CHANGELOG.md, src/providers/docker_test/plugin_test.py
不然遇到这种测试超时的插件 <https://registry.nonebot.dev/plugin/nonebot-plugin-todo-nlp:nonebot_plugin_todo_nlp> 也不知道发生了什么。
=> fix(plugin_test): 超时后仍需读取 stdout 与 stderr 的内容

CHANGELOG.md, src/plugins/github/plugins/config/utils.py, src/plugins/github/plugins/publish/validation.py, src/providers/docker_test/__init__.py, src/providers/docker_test/plugin_test.py, src/providers/store_test/validation.py, tests/github/config/process/test_config_check.py, tests/github/publish/process/test_publish_pull_request.py, tests/github/publish/utils/test_publish_resolve_conflict_pull_requests.py, tests/github/publish/utils/test_trigger_registry_update.py, tests/github/publish/utils/test_validate_info_from_issue.py, tests/utils/docker_test/test_docker_plugin_test.py, tests/utils/docker_test/test_plugin_test.py, tests/utils/store_test/output.json, tests/utils/store_test/output_failed.json
=> fix(docker_test): 修复 Docker Test 报错未捕获的问题

CHANGELOG.md, src/providers/models.py, tests/github/config/process/test_config_check.py, tests/github/config/utils/test_config_update_file.py, tests/github/publish/process/test_publish_pull_request.py, tests/github/publish/utils/test_trigger_registry_update.py
仅需要修改 StoreTestResult 中的数据。
为了方便验证，之前 #283 中直接将获取到的 metadata 中字段改名为 desc 了。
现在与 <https://github.com/nonebot/registry/blob/ac63c4e1d240004211e94b239bc016df18e89033/src/types/results.ts#L23-L30> 保持一致。
=> fix: 修复插件测试结果中插件元数据 description 字段名称不正确的问题

CHANGELOG.md, src/providers/docker_test/plugin_test.py, tests/utils/docker_test/test_extract_version.py
遇到了一个奇怪的输出，缺少了最前面的版本信息。
```log
项目 nonebot-plugin-todo-nlp 创建失败：
- Installing nonebot-plugin-todo-nlp (0.1.9)
Writing lock file
执行命令超时Warning: Validation of the RECORD file of playwright-1.49.0-py3-none-manylinux1_x86_64.whl failed. Please report to the maintainers of that package so they can fix their build process. Details:
In /root/.cache/pypoetry/artifacts/61/92/84/cc2c725417ce7948df6ef0ea8ee84b79dc02f0192924e28bc146c4d55e/playwright-1.49.0-py3-none-manylinux1_x86_64.whl, playwright/driver/LICENSE is not mentioned in RECORD
In /root/.cache/pypoetry/artifacts/61/92/84/cc2c725417ce7948df6ef0ea8ee84b79dc02f0192924e28bc146c4d55e/playwright-1.49.0-py3-none-manylinux1_x86_64.whl, playwright/driver/node is not mentioned in RECORD
```
这是正常的输出：
```log
项目 nonebot-plugin-nailongremove 创建失败： …
```
=> fix(plugin_test): 修复插件测试日志不全时版本号匹配失败的问题

.github/workflows/main.yml, examples/store-test.yml, pyproject.toml, uv.lock
这样可以避免本地开发时因为忘记使用 uv sync --all-extras 命令导致测试出错。
以前是为了降低 noneflow docker 镜像的大小，现在已经弃疗了。
=> chore(deps): 移除 optional-dependencies

CHANGELOG.md, pyproject.toml, src/plugins/github/plugins/publish/render.py, src/providers/constants.py, src/providers/models.py, src/providers/store_test/store.py, tests/plugins/github/config/process/test_config_check.py, tests/plugins/github/config/utils/test_config_update_file.py, tests/plugins/github/publish/process/test_publish_check.py, tests/plugins/github/publish/render/test_publish_render_data.py, tests/providers/store_test/test_step_summary.py, tests/providers/store_test/test_validate_plugin.py
应该是这个效果，之前时间没带时区，都不知道具体是什么时间。
> Plugin: 帮助
**✅ 所有测试通过，一切准备就绪！**
<details>
<summary>详情</summary>
<pre><code><li>✅ 项目 <a href="https://github.com/he0119/nonebot-plugin-treehelp">主页</a> 返回状态码 200。</li><li>✅ 项目 <a href="https://pypi.org/project/nonebot-plugin-treehelp/">nonebot-plugin-treehelp</a> 已发布至 PyPI。</li><li>✅ 插件类型: application。</li><li>✅ 插件支持的适配器: 所有。</li><li>✅ 插件发布时间：2024-07-13 12:41:40 CST。</li><li>✅ 插件版本号: 0.5.0。</li><li>✅ 插件 <a href="https://github.com/owner/repo/actions/runs/123456">加载测试</a> 通过。</li></code></pre>
</details>
---
💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
💡 当插件加载测试失败时，请发布新版本后勾选插件测试勾选框重新运行插件测试。
💪 Powered by [NoneFlow](https://github.com/nonebot/noneflow)
=> fix: 统一数据显示顺序并且时间添加时区

src/plugins/github/handlers/git.py, tests/plugins/github/handlers/test_git_handler.py, tests/plugins/github/handlers/test_github_handler.py, tests/plugins/github/handlers/test_issue_handler.py, tests/plugins/github/utils.py
之前把 handlers 都拆出来了，现在加点相关测试。以后测试其他部分可以用 mock_handler 去测试，应该能简化不少。
需要等前一个 PR 合并之后才合并这个。
=> test: 添加 handlers 的测试

CHANGELOG.md, src/plugins/github/plugins/publish/constants.py, src/plugins/github/plugins/publish/render.py, src/plugins/github/plugins/publish/templates/render_data.md.jinja, tests/plugins/github/config/process/test_config_check.py, tests/plugins/github/publish/process/test_publish_check.py, tests/plugins/github/publish/render/test_publish_render_data.py
除了插件，适配器也会用到，所以应该删掉插件的前缀。#330 并没有修改好。
> Plugin: 帮助
**✅ 所有测试通过，一切准备就绪！**
<details>
<summary>详情</summary>
<pre><code><li>✅ 项目 <a href="https://github.com/he0119/nonebot-plugin-treehelp">主页</a> 返回状态码 200。</li><li>✅ 项目 <a href="https://pypi.org/project/nonebot-plugin-treehelp/">nonebot-plugin-treehelp</a> 已发布至 PyPI。</li><li>✅ 标签: render-#ffffff。</li><li>✅ 插件类型: application。</li><li>✅ 插件支持的适配器: 所有。</li><li>✅ 插件 <a href="https://github.com/owner/repo/actions/runs/123456">加载测试</a> 通过。</li><li>✅ 版本号: 0.5.0。</li><li>✅ 发布时间：2024-07-13 12:41:40 CST。</li></code></pre>
</details>
---
💡 如需修改信息，请直接修改 issue，机器人会自动更新检查结果。
💡 当插件加载测试失败时，请发布新版本后勾选插件测试勾选框重新运行插件测试。
💪 Powered by [NoneFlow](https://github.com/nonebot/noneflow)
> Adapter: 大别野
**✅ 所有测试通过，一切准备就绪！**
<details>
<summary>详情</summary>
<pre><code><li>✅ …
=> fix: 重新调整数据显示顺序和文本

CHANGELOG.md, src/plugins/github/handlers/git.py, src/plugins/github/handlers/github.py, src/plugins/github/plugins/publish/utils.py, src/plugins/github/plugins/resolve/__init__.py, tests/plugins/github/handlers/test_git_handler.py, tests/plugins/github/publish/process/test_publish_check.py, tests/plugins/github/resolve/test_resolve_pull_request.py, tests/plugins/github/utils.py
分支和拉取请求绑定起来，分支不存在才能创建拉取请求。
fixed #345
=> fix: 修复在评论议题后立即关闭拉取请求，拉取请求会被再次创建的问题

examples/noneflow.yml
并且是拉取请求相关操作时，会取消之前正在运行的操作。
比如，当评论之后马上关闭拉取请求，这个时候评论触发的操作还在进行，拉取请求的操作又被触发时，之前评论的操作会因为是同一个并发组被取消。
如果此时拉取请求的操作还在排队，这时候分支还存在，因为之前将拉取请求和分支绑定，也不会新建拉取请求。待拉取请求触发的操作运行后，会自动删除相关分支。
fixed #345
=> fix: 将拉取请求和相关议题放在同一个并发组

CHANGELOG.md, src/plugins/github/handlers/issue.py, src/plugins/github/plugins/resolve/__init__.py, tests/plugins/github/resolve/test_resolve_close_issue.py, tests/plugins/github/utils.py
如果议题的 state_reason 不一致时还需要重新关闭一次。
=> fix: 修复议题已经被关闭时无法正确设置为 not_planned 的问题

CHANGELOG.md, src/providers/validation/models.py, tests/providers/validation/fields/test_plugin_supported_adapters.py
唉，用户输入。
https://github.com/nonebot/nonebot2/issues/3456
https://github.com/bananaxiao2333/nonebot-plugin-uptime-kuma-puller/blob/cd07468e6ff6f48a7ecd9bc8a442889d36dc1a11/nonebot_plugin_uptime_kuma_puller/__init__.py#L30
=> fix: 修复插件元数据适配器中存在非字符串报错的问题

CHANGELOG.md, src/plugins/github/handlers/github.py, src/plugins/github/handlers/issue.py, src/plugins/github/plugins/config/__init__.py, src/plugins/github/plugins/publish/__init__.py, src/plugins/github/plugins/publish/constants.py, src/plugins/github/plugins/publish/render.py, src/plugins/github/plugins/publish/templates/comment.md.jinja, src/plugins/github/plugins/publish/utils.py, src/plugins/github/plugins/remove/__init__.py, tests/conftest.py, tests/plugins/github/config/process/test_config_check.py, tests/plugins/github/config/utils/test_config_update_file.py, tests/plugins/github/handlers/test_github_handler.py, tests/plugins/github/handlers/test_issue_handler.py, tests/plugins/github/publish/process/test_publish_check_plugin.py, tests/plugins/github/publish/render/test_publish_render.py, tests/plugins/github/publish/render/test_publish_render_data.py, tests/plugins/github/publish/render/test_publish_render_error.py, tests/plugins/github/publish/utils/test_comment_issue.py, tests/plugins/github/publish/utils/test_history_workflow.py, tests/providers/docker_test/test_docker_plugin_test.py, tests/providers/store_test/test_step_summary.py, tests/providers/store_test/test_validate_plugin.py
=> feat: 在 Noneflow 工作流评论处增设 Noneflow 运行历史

.github/renovate.json5
这样以下两个 PR 会合并。
- https://github.com/nonebot/noneflow/pull/395
- https://github.com/nonebot/noneflow/pull/396
=> chore(renovate): 更新 Python 版本时还需要更新 pep621 的 python

CHANGELOG.md, src/plugins/github/plugins/publish/render.py, tests/plugins/github/publish/process/test_publish_check.py, tests/plugins/github/publish/render/test_publish_render.py, tests/plugins/github/publish/render/test_publish_render_data.py, tests/plugins/github/publish/render/test_publish_render_error.py
任何时候都应该显示历史测试，因为 #394 和 #401 依赖其提供数据。
=> fix: 修复机器人/适配器发布时没有历史测试的问题
