main.py
src/globals.py
src/models.py
src/process.py
tests/conftest.py
tests/models/test_adapter.py
tests/models/test_name.py
tests/process/test_issues.py
tests/process/test_pull_request.py

通过 `module_name` 与 `project_link` 来检测是否重复发布。

feat: 检测是否重复发布

---

.pre-commit-config.yaml
CHANGELOG.md
poetry.lock
pyproject.toml
src/process.py
src/utils.py
tests/process/test_issues.py

fix: 修复未同时修改议题与拉取请求标题的问题

---

.coveragerc
tests/models/test_adapter.py
tests/models/test_bot.py
tests/models/test_name.py
tests/models/test_plugin.py
tests/models/test_tags.py
tests/process/test_publish_check.py
tests/process/test_pull_request.py
tests/utils/test_get_pull_requests_by_label.py
tests/utils/test_get_type.py

test: 提高测试覆盖率

---

src/bot.py
src/constants.py
tests/process/test_publish_check.py
tests/utils/test_comment_issue.py

feat: 添加修改提示

---

poetry.lock
pyproject.toml

chore(deps): 升级依赖至最新

---

CHANGELOG.md
src/bot.py

需要等创建完拉取请求并打上标签后修改议题标题，不然会因为修改议题触发 Actions 导致标签没有正常打上。

fix: 修复拉取请求标签没有打上的问题

---

Dockerfile

fix: 再次尝试修复 git 问题

---

.github/workflows/main.yml
Dockerfile
poetry.lock
pyproject.toml
src/utils.py

chore(deps): 升级 Python 至 3.11 版本

---

plugin_test.py

- 无论加载是否正常均输出所有日志
- 截断输出内容防止评论过长

improve: 优化日志

---

src/plugins/publish/validation.py
tests/models/test_bot.py
tests/models/test_tags.py

- 提示标签为 JSON 格式
- 无法匹配到数据时显示可读字段名称

improve: 优化评论内容

---

CHANGELOG.md
Dockerfile

build: 设置时区为中国

---

CHANGELOG.md
bot.py

feat: 遵守 debug logging 的设置

---

CHANGELOG.md
src/plugins/publish/__init__.py

improve: 审查通过后如果可合并则直接合并

---

CHANGELOG.md
plugin_test.py

fix: 修复插件测试数据匹配问题

---

CHANGELOG.md
plugin_test.py

通过插件配置项提供插件配置
```env
driver=~fastapi
```

feat: 支持测试时设置插件配置项

---

CHANGELOG.md
src/plugins/publish/__init__.py
src/plugins/publish/constants.py
src/plugins/publish/validation.py
tests/publish/models/test_adapter.py
tests/publish/models/test_name.py
tests/publish/process/test_publish_check.py

feat: 限制名称的长度不超过 50 个字符

---

CHANGELOG.md
Dockerfile
README.md
poetry.lock
pyproject.toml
src/plugins/publish/__init__.py
src/plugins/publish/utils.py
tests/publish/process/test_auto_merge.py
tests/publish/process/test_publish_check.py

feat: 提交前先运行 pre-commit 统一格式

---

src/utils/store_test/models.py
src/utils/store_test/validation.py

is_official 的值是手动添加的，所以需要继承之前的值。

fix: 继承插件 is_official 的值

---

poetry.lock
pyproject.toml
src/utils/store_test/__main__.py
src/utils/store_test/constants.py
src/utils/store_test/models.py
src/utils/store_test/store.py
src/utils/store_test/utils.py
src/utils/store_test/validation.py

feat: 生成新的商店插件列表

---

CHANGELOG.md
README.md
src/plugins/publish/__init__.py
src/plugins/publish/config.py
src/plugins/publish/utils.py
src/utils/store_test/__main__.py
src/utils/store_test/store.py
tests/conftest.py
tests/publish/process/test_pull_request.py

feat: 拉取请求合并后触发 registry 更新

---

README.md
src/utils/store_test/constants.py
src/utils/store_test/models.py
src/utils/store_test/store.py
src/utils/store_test/utils.py
src/utils/store_test/validation.py

增加 info 字段，并删除 plugin 字段。
同时输出最紧凑的 JSON 格式。
从仓库插件列表中获取最少的数据，为以后做准备。

change: 调整商店测试输出格式

---

CHANGELOG.md
src/plugins/publish/templates/render_error.md.jinja
src/utils/validation/errors.py
src/utils/validation/models.py
src/utils/validation/utils.py
tests/publish/render/test_render_error.py

feat: 检查网址时返回具体的报错信息

---

CHANGELOG.md
src/utils/store_test/store.py
src/utils/store_test/validation.py
tests/utils/store_test/test_validate_plugin.py

这个名称本就是保存在 plugins.json 中，所需不需要额外的 plugin 说明。

fix: 修正字段名称为 skip_test

---

CHANGELOG.md
src/utils/validation/__init__.py
src/utils/validation/constants.py
src/utils/validation/errors.py
src/utils/validation/models.py
src/utils/validation/utils.py
tests/utils/validation/test_bot.py
tests/utils/validation/test_name.py
tests/utils/validation/test_tags.py

feat: 翻译 Pydantic 验证错误信息

---

CHANGELOG.md
src/plugins/publish/templates/render_error.md.jinja
src/utils/validation/__init__.py
src/utils/validation/constants.py
src/utils/validation/models.py
tests/publish/render/test_render_error.py
tests/utils/validation/test_plugin_supported_adapters.py
tests/utils/validation/utils.py

fix: 修复支持的适配器字段验证信息错误的问题

---

CHANGELOG.md
src/utils/validation/errors.py
src/utils/validation/models.py
tests/utils/validation/test_plugin_supported_adapters.py

fix: 修复因 missing_adapters 的类型为集合导致的编码报错

---

CHANGELOG.md
src/utils/plugin_test.py

fix(plugin_test): 修复 Fake Driver 的 server_app 方法抛出异常导致部分插件测试报错的问题

---

examples/noneflow.yml

同步 <https://github.com/nonebot/nonebot2/pull/2677> 的更新。

feat: 添加 reaction 响应提示

---

.github/workflows/docker-test.yml

ci: 修复 nonetest 发布失败的问题

---

CHANGELOG.md
pyproject.toml
src/plugins/github/plugins/publish/validation.py
src/providers/validation/models.py
tests/utils/validation/fields/test_homepage.py
tests/utils/validation/test_bot.py
tests/utils/validation/utils.py

feat: 通过名称加主页避免机器人重复

---

src/plugins/github/plugins/remove/validation.py
src/providers/constants.py
src/providers/models.py
src/providers/store_test/constants.py
src/providers/store_test/store.py
src/providers/store_test/validation.py
src/providers/validation/__init__.py
src/providers/validation/models.py
tests/utils/store_test/test_store_test.py
tests/utils/store_test/test_validate_plugin.py

统一给 registry 使用的模型加上了 Registry 前缀。

refactor: 重命名模型名称并增加了几个类型别名

---

src/plugins/github/plugins/publish/utils.py
src/plugins/github/plugins/remove/utils.py
tests/github/publish/utils/test_publish_resolve_conflict_pull_requests.py
tests/github/remove/utils/test_remove_resolve_pull_requests.py
tests/github/remove/utils/test_update_file.py

顺便调整了 remove 插件中的 update_file。

fix: 修复解决冲突验证失败时未能正常跳过的问题

---

Dockerfile

build: 手动指定 project 目录

---

CHANGELOG.md
src/providers/store_test/store.py
src/providers/store_test/utils.py
tests/utils/store_test/test_store_test.py

fix(store_test): 修复商店测试中获取 PyPI 数据出错会直接退出的问题

---

CHANGELOG.md
src/providers/store_test/validation.py
tests/utils/store_test/test_validate_plugin.py

更新 author_id, tags 和 is_official 数据的位置不对。

fix(store_test): 修复商店测试时出现缺少 author_id 报错的问题

---

CHANGELOG.md
src/providers/docker_test/__init__.py
tests/utils/docker_test/test_docker_plugin_test.py

fix(docker_test): 修复 Docker 容器测试后未正常清理的问题

---

CHANGELOG.md
src/plugins/github/constants.py
src/plugins/github/plugins/config/__init__.py
src/plugins/github/plugins/config/constants.py
src/plugins/github/plugins/config/utils.py
src/plugins/github/plugins/publish/__init__.py
src/providers/utils.py
tests/github/config/conftest.py
tests/github/config/process/test_config_auto_merge.py
tests/github/config/process/test_config_check.py
tests/github/config/utils.py
tests/github/config/utils/test_config_update_file.py

配合 <https://github.com/nonebot/registry/pull/28>。
close #286

feat: 支持修改配置并重新测试

---

src/plugins/github/plugins/config/__init__.py
tests/github/config/process/test_config_check.py

fix(github/config): 补上插件测试按钮

---

CHANGELOG.md
src/providers/docker_test/__init__.py
src/providers/validation/constants.py
tests/utils/docker_test/test_docker_plugin_test.py
tests/utils/validation/fields/test_missing.py
tests/utils/validation/utils.py

fix: 修复 Docker Test 报错后仍无法运行的问题

---

CHANGELOG.md
src/plugins/github/plugins/publish/utils.py
tests/github/publish/process/test_publish_check.py

之前如果已经添加了插件测试项，则重新测试不会提示用户测试进行中。

fix: 修复重新测试时没有提示测试进行中的问题

---

src/plugins/github/models/git.py
src/plugins/github/models/github.py
src/plugins/github/models/issue.py
src/plugins/github/plugins/config/__init__.py
src/plugins/github/plugins/publish/__init__.py
src/plugins/github/plugins/publish/utils.py
src/plugins/github/plugins/remove/__init__.py
src/plugins/github/plugins/remove/utils.py
src/plugins/github/plugins/resolve/__init__.py
tests/github/config/process/test_config_auto_merge.py
tests/github/publish/process/test_auto_merge.py
tests/github/publish/process/test_publish_check.py
tests/github/remove/process/test_remove_auto_merge.py

尽量将每个 GitHub API 请求放入方法中简化写法，并且将 run_shell_command 都放入 GitHandler 中。

refactor: 优化 handler 相关函数

---

CHANGELOG.md
src/plugins/github/depends/__init__.py
tests/github/remove/process/test_remove_check.py

fix: 修复机器人修改议题等操作时仍会触发响应器的问题

---

CHANGELOG.md
src/plugins/github/depends/__init__.py
src/plugins/github/depends/utils.py
src/plugins/github/plugins/config/__init__.py
src/plugins/github/plugins/publish/__init__.py
src/plugins/github/plugins/remove/__init__.py
src/plugins/github/plugins/resolve/__init__.py
tests/github/config/process/test_config_pull_request.py

fix: 修复合并插件配置后没有删除对应分支和关闭议题的问题

---

CHANGELOG.md
src/plugins/github/plugins/publish/__init__.py
tests/github/publish/process/test_publish_check.py

当信息验证做完之后，马上根据验证结果评论议题，给用户第一时间的反馈。

feat: 发布检查时第一时间评论议题并修改标题

---

CHANGELOG.md
examples/noneflow.yml
pyproject.toml
src/plugins/github/plugins/publish/__init__.py
src/plugins/github/plugins/remove/__init__.py
src/plugins/github/plugins/resolve/__init__.py
tests/github/config/process/test_config_pull_request.py
tests/github/publish/process/test_publish_check.py
tests/github/remove/process/test_remove_check.py
tests/github/remove/process/test_remove_pull_request.py
uv.lock

remove: 移除 pre-commit 相关操作

---

.pre-commit-config.yaml
pyproject.toml
src/providers/validation/__init__.py
src/providers/validation/utils.py

新增 flake8-type-checking 规则，并更新 ruff 版本。

style: 更新 ruff 和 pyright 配置

---

CHANGELOG.md
docker/nonetest.dockerfile

poetry 2.0.0 没法 export 了，暂时固定版本号。

fix: 修复获取依赖失败的问题

---

pyproject.toml
src/plugins/github/plugins/publish/render.py
src/plugins/github/plugins/publish/templates/comment.md.jinja
tests/plugins/github/config/process/test_config_check.py
tests/plugins/github/publish/process/test_publish_check.py
tests/plugins/github/publish/process/test_publish_check_plugin.py
tests/plugins/github/publish/render/test_publish_render.py
tests/plugins/github/publish/render/test_publish_render_data.py
tests/plugins/github/publish/render/test_publish_render_error.py

- 新增插件审核评论主页入口卡片
- 新增 inline-snapshot 在 pyproject.toml 里的 tool 设置项
- 更新相关测试快照

feat: 新增插件审核评论的主页入口卡片

---

src/plugins/github/handlers/git.py
src/plugins/github/plugins/config/__init__.py
src/plugins/github/plugins/config/utils.py
src/plugins/github/plugins/publish/utils.py
src/plugins/github/plugins/remove/__init__.py
src/plugins/github/plugins/remove/utils.py
tests/plugins/github/config/process/test_config_check.py
tests/plugins/github/config/utils/test_config_update_file.py
tests/plugins/github/handlers/test_git_handler.py
tests/plugins/github/handlers/test_issue_handler.py
tests/plugins/github/publish/process/test_publish_check.py
tests/plugins/github/publish/process/test_publish_check_plugin.py
tests/plugins/github/publish/utils/test_publish_resolve_conflict_pull_requests.py
tests/plugins/github/remove/process/test_remove_check.py
tests/plugins/github/remove/utils/test_remove_resolve_pull_requests.py
tests/plugins/github/remove/utils/test_update_file.py
tests/plugins/github/resolve/test_resolve_pull_request.py
uv.lock

fix: 更新文件时手动添加对应文件

---

examples/store-test.yml

fix: 修复插件测试和注册更新的条件判断逻辑
